# Generated by Django 3.2.8 on 2021-10-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_assignment_filesubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='file',
            field=models.FileField(blank=True, default='settings.MEDIA_ROOT/foo/FloatMoodle.pdf', upload_to='media'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='file_name',
            field=models.CharField(default='problem_statement', max_length=100),
        ),
        migrations.AddField(
            model_name='assignment',
            name='link',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='assignment',
            name='statement',
            field=models.CharField(default='', max_length=300),
        ),
    ]
