# Generated by Django 3.2.8 on 2021-10-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_assignment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesubmission',
            name='feedback',
            field=models.CharField(default='Your Feedback Appears Here', max_length=500),
        ),
        migrations.AlterField(
            model_name='filesubmission',
            name='file',
            field=models.FileField(blank=True, upload_to='submissions'),
        ),
    ]
