# Generated by Django 3.2.8 on 2021-10-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20211019_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesubmission',
            name='corrected',
            field=models.CharField(default='NO', max_length=10),
        ),
    ]
