# Generated by Django 3.2.8 on 2021-11-22 14:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20211020_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filesubmission',
            name='sub_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
