# Generated by Django 3.2.8 on 2021-11-24 11:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0013_auto_20211122_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='TAjoincode',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='TAs',
            field=models.ManyToManyField(related_name='ta_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
