# Generated by Django 3.2.8 on 2021-11-27 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_chat_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dm',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.chat'),
        ),
    ]
