# Generated by Django 3.2.8 on 2021-11-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_alter_dm_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dm',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
