# Generated by Django 3.2.8 on 2021-11-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_auto_20211127_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='enabled',
            field=models.CharField(default='YES', max_length=4),
        ),
    ]
