# Generated by Django 3.2.8 on 2021-11-28 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0023_assignment_feedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TA_Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_create', models.CharField(default='NO', max_length=4)),
                ('forum_create', models.CharField(default='NO', max_length=4)),
                ('add_students', models.CharField(default='NO', max_length=4)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
